// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xgndtx1wAp1Kt3H67Xxeiq
import * as React from "react";
import { CmsCredentialsProvider } from "@plasmicpkgs/plasmic-cms"; // plasmic-import: OREVbGCcgN/codeComponent
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css"; // plasmic-import: qF0uJxFztB/codeComponent
import { StrapiCredentialsProvider } from "@plasmicpkgs/plasmic-strapi"; // plasmic-import: Nz3wPi974V7/codeComponent

export default function GlobalContextsProvider(props) {
  const {
    children,
    cmsCredentialsProviderProps,
    embedCssProps,
    strapiCredentialsProviderProps
  } = props;
  return (
    <CmsCredentialsProvider
      {...cmsCredentialsProviderProps}
      databaseId={
        cmsCredentialsProviderProps &&
        "databaseId" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.databaseId
          : "qTu5s8ndUcepHiL9JzmKuY"
      }
      databaseToken={
        cmsCredentialsProviderProps &&
        "databaseToken" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.databaseToken
          : "F8u924JXVwAKem68FJeKIkaBc13bjueDReijgkXYditE3n77KxeISMFDQA6TFsGKu76j4lXqXBEF8wxG0lw"
      }
      host={
        cmsCredentialsProviderProps && "host" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.host
          : "https://studio.plasmic.app"
      }
      locale={
        cmsCredentialsProviderProps && "locale" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.locale
          : undefined
      }
    >
      <EmbedCss
        {...embedCssProps}
        css={
          embedCssProps && "css" in embedCssProps
            ? embedCssProps.css
            : undefined
        }
      >
        <StrapiCredentialsProvider
          {...strapiCredentialsProviderProps}
          host={
            strapiCredentialsProviderProps &&
            "host" in strapiCredentialsProviderProps
              ? strapiCredentialsProviderProps.host
              : "http://localhost:1337"
          }
          token={
            strapiCredentialsProviderProps &&
            "token" in strapiCredentialsProviderProps
              ? strapiCredentialsProviderProps.token
              : "9054f5a5442381ed5fb156f0cbe28ec42c49efb47e6a7a603701e03abdbd6bd482fc2c72f6133c9fcf50c8456212e150768d163c30b62dbb2edb2a2d37ef1b0748b6e4d68728b48dea0cd80f935f7ca37d969f1f0906641fec39e066f506ef4cfb8ca8049eac315dd034f9e7b545cd025f9be9bc04e237c7302c598733f8a664"
          }
        >
          {children}
        </StrapiCredentialsProvider>
      </EmbedCss>
    </CmsCredentialsProvider>
  );
}
